config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  resources :links do
    member do
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end

  root to: "links#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :links
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user
  
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  include ApplicationHelper
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to root_path
  end
  
  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # 平方公尺換算成坪數
  def custom_time_ago_in_words(set_date)
    get_hour = (Time.now - set_date).div(3600)
  	get_second = (((Time.now - set_date)/3600 - get_hour) * 60).round()
  	return get_hour.to_s + "小時" + get_second.to_s + "分"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
  <div class="comments_wrapper clearfix">
    <div class="pull-left">
     <p class="lead"><%= comment.body %></p>
     <p>
       <small>
         Submitted 
         <strong>
           <%= custom_time_ago_in_words(comment.created_at) %> ago
         </strong> by <%= comment.user.name %>
       </small>
     </p>
    </div>
  
    <div class="btn-group pull-right">
     <% if comment.user == current_user -%>
       <%= link_to 'Destroy', comment, method: :delete, \
                              date: { confirm: 'Are you sure?' }, \
                              class: "btn btn-sm btn-default" %>
     <% end %>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :link_id %>
    <%= form.number_field :link_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Navbar版面的設定-->
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
      <a href="/" class="navbar-brand">
        <i class="fas fa-book"></i>
        <%= link_to "Reddit", root_path %>
      </a>
      <% if user_signed_in? %>
        <!--ms-* 是靠右、me-* 是靠左-->
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <%= link_to 'Submit link', new_link_path, class: "btn btn-outline-primary mx-2" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Account', edit_user_registration_path, class: "btn btn-outline-secondary mx-2" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class: "btn btn-outline-success mx-2" %>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav ms-auto">
          <li>
            <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-outline-info mx-2" %>
          </li>
          <li>
            <%= link_to 'Sign in', new_user_session_path, class: "btn btn-outline-danger mx-2" %>
          </li>
        </ul>
      <% end %>
    </nav>
    
    <!--yield的版面設定-->
    <div id="main_content" class="container">
      <% flash.each do |name, msg| %>
        <% content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>
      <div id="content" class="col-md-9 center-black">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "標題" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "網址" %>
    <%= form.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "傳送", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<% @links.each do |link| %>
  <div class="card">
    <div class="card-header fs-2">
      <%= link_to link.title, link %>
    </div>
    <div class="card-body">
      <p class="card-title fs-5">
        撰寫人：<%= link.user.name %>
      </p>
      <p class="card-title fs-6">
        最後上傳時間：<%= custom_time_ago_in_words(link.created_at) %> 之前
      </p>
      
      <div class="btn-group">
        <a class="btn btn-outline-dark btn-sm" href="<%= link.url %>">Visit Link</a>
          <%= link_to like_link_path(link), method: :put, \
                                            class: "btn btn-outline-dark btn-sm" do %>
            <span class="glyphicon glyphicon-chevron-up"></span>
            Upvote
            <%= link.get_upvotes.size %>
          <% end %>
          <%= link_to dislike_link_path(link), method: :put \
                                 , class: "btn btn-outline-dark btn-sm" do %>
            <span class="glyphicon glyphicon-chevron-down"></span>
            Downvote
            <%= link.get_downvotes.size %>
          <% end %>
      </div>
    
    </div>
  </div>
<% end %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to '返回到首頁', links_path %>

app/views/links/show.html.erb
<div class="page-header">
  <h1>
    <a href="<%= @link.url %>">
      <%= @link.title %>
    </a>
    <br> 
    <small>
      Submitted by 
      <%= @link.user.name %>
    </small>
  </h1>
</div>

<div class="btn-group">
  <%= link_to 'Visit URL', @link.url, class: "btn btn-primary" %>
</div>

<% if @link.user == current_user -%>
  <div class="btn-group">
  <%= link_to 'Edit', edit_link_path(@link), class: "btn btn-outline-dark" %>
  <%= link_to 'Destroy', @link, method: :delete, data: {confirm: 'Are you sure?' } \
                                               , class: "btn btn-outline-dark" %>
  </div>
<% end %>

<div class="btn-group pull-right">
  <%= link_to like_link_path(@link), method: :put, class: "btn btn-outline-dark btn-sm" do %>
    <span class="glyphicon glyphicon-chevron-up"></span>
    Upvote
    <%= @link.get_upvotes.size %>
  <% end %>
  <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-outline-dark btn-sm" do %>
    <span class="glyphicon glyphicon-chevron-down"></span>
    Downvote
    <%= @link.get_downvotes.size %>
  <% end %>
</div>  

<h3 class="comments_title">
  <%= @link.comments.count %> Comments
</h3>

<div id="comments">
  <%= render :partial => @link.comments %>
</div>
<%= simple_form_for [@link, Comment.new]  do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <br>
  <%= f.submit "Add Comment", class: "btn btn-primary" %>
<% end %>